### PR TITLE
Erik Polsean - Setup Skeleton

### PR DESCRIPTION
**Pull request by epolsean**

### CODE REVIEW

**Comment by epolsean** [comment]
Don't be afraid to delete my branches after merges

**Comment by polseane9067** [comment]
Ready to merge

**Comment by polseane9067** [comment]
Ready to merge

**Comment by polseane9067** [comment]
Ready to merge

**Comment by epolsean** [comment]
Ready to merge

**Review by erchiggins — APPROVED** [review]

**Pull request merged**
